-- GENRE DDL
DROP TABLE GENRE CASCADE CONSTRAINTS;
DROP SEQUENCE GENRE_SEQ;
CREATE SEQUENCE GENRE_SEQ MAXVALUE 999 NOCACHE NOCYCLE;
CREATE TABLE GENRE(
    gId NUMBER(3) PRIMARY KEY,
    gName VARCHAR2(30) NOT NULL
);
SELECT * FROM GENRE;

-- GENRE DUMMY
-- GENRE(영화장르) DUMMY
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '다큐멘터리');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '액션');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '모험');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '코미디');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '가족');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '드라마');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '멜로/로맨스');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '범죄');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '느와르');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '판타지');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '공포');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '스릴러');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '공연실황');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, 'SF');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '전쟁');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '컬트');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '서부');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '뮤지컬');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '무성');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '무협');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '미스터리');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '서사');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '실험');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '에로');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '서스펜스');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '애니메이션');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '블랙코미디');
INSERT INTO GENRE (gId, gName) VALUES (GENRE_SEQ.NEXTVAL, '실화');
COMMIT;