-- GRADE DDL
DROP TABLE GRADE CASCADE CONSTRAINTS;
DROP SEQUENCE GRADE_SEQ;
CREATE SEQUENCE GRADE_SEQ MAXVALUE 9 NOCACHE NOCYCLE;
CREATE TABLE GRADE(
    grId NUMBER(1) PRIMARY KEY,
    grName VARCHAR2(30) NOT NULL
);
SELECT * FROM GRADE;
-- GRADE DUMMY
INSERT INTO GRADE (grId, grName) VALUES (GRADE_SEQ.NEXTVAL, '전체관람가');
INSERT INTO GRADE (grId, grName) VALUES (GRADE_SEQ.NEXTVAL, '12세 이상 관람가');
INSERT INTO GRADE (grId, grName) VALUES (GRADE_SEQ.NEXTVAL, '15세 이상 관람가');
INSERT INTO GRADE (grId, grName) VALUES (GRADE_SEQ.NEXTVAL, '청소년 관람불가');
INSERT INTO GRADE (grId, grName) VALUES (GRADE_SEQ.NEXTVAL, '제한상영가');
COMMIT;